---
title: "HW 01 - Airbnb listings in Edinburgh"
author: "Sara Bond"
date: "July 13th, 2022"
output: github_document
---

## Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse)
library(dsbox)
```

## Exercises

### Exercise 1

There are `r nrow(edibnb)` rows in the data set. 

### Exercise 2

Each row represents an airbnb. 

### Exercise 3

Remove this text, and add your answer for Exercise 3 here.

```{r prices-neighbourhoods}
# remove this comment and add the code for Exercise 3 here
```

### Exercise 4

Remove this text, and add your answer for Exercise 4 here.

```{r top-5-median}
# remove this comment and add the code for Exercise 4 here
```

```{r top-5-median-plot}
# remove this comment and add the code for Exercise 4 here
```

```{r top-5-median-summary-stats}
# remove this comment and add the code for Exercise 4 here
```

### Exercise 5

Remove this text, and add your answer for Exercise 5 here.

```{r review-scores-rating}
# remove this comment and add the code for Exercise 5 here
```
